version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - npm install npm -g
  build:
    commands:
      - ng build

artifacts:
  files:
    - dist/*
  base-directory: 'dist'
  bucket-name: sample-python-app-codebuild
