version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - npm install npm -g
  build:
    commands:
      - npm run build

artifacts:
  files:
    - build/*
  discard-paths: yes
  bucket-name: sample-python-app-codebuild
